- fix in checking is netforking is up.
Changed files:
    socks5.init -> 1.4

diff --git a/socks5.init b/socks5.init
--- a/socks5.init
+++ b/socks5.init
@@ -16,7 +16,10 @@
 [ -f /etc/sysconfig/socks5 ] && . /etc/sysconfig/socks5
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Socks5 can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
